sonar.projectKey=WhereAmI14_linux-admin-tools
sonar.organization=ivan14sr
sonar.projectName=linux-admin-tools slow-mysqlqueries
sonar.sources=slow_query_review.py
sonar.tests=temp-files-and-tests/tests
sonar.sourceEncoding=UTF-8
sonar.test.inclusions=temp-files-and-tests/tests/**/*.py
sonar.exclusions=temp-files-and-tests/tests/fixtures/**
